#!/bin/bash

sudo apt update
sudo apt install git -y
pwd
rm -rf *
sudo git clone https://github.com/naveenraj7695/docker-test.git
ls
sudo cp -R docker-test/* .
ls
sudo docker build . -t 381491915376.dkr.ecr.eu-west-2.amazonaws.com/mytest
sudo aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 381491915376.dkr.ecr.eu-west-2.amazonaws.com
sudo docker push 381491915376.dkr.ecr.eu-west-2.amazonaws.com/mytest
sudo docker stop $(sudo docker ps)
sudo docker rm $(sudo docker ps -a)
sudo docker run -d -p 80:80 381491915376.dkr.ecr.eu-west-2.amazonaws.com/mytest
